### ISSUE TITLE
Invisible blockade in Bar

### ISSUE THREAD

**Issue by Filmsplitter341** [DDMers/NSV13#111]
## Round ID:
20

## Reproduction:
In the Bar infront of the Booze-O-Mat is a invisible thing blocking the path. The photo shows the exact location. 
![image](https://user-images.githubusercontent.com/57299079/68075538-2dba5f80-fda9-11e9-8f29-374bded1deb8.png)

**Comment by francinum** [comment]
Resolved in #107
