### ISSUE TITLE
Durasteel and Duranium conflation in construction

### ISSUE THREAD

**Issue by ArbyTheDragon** [DDMers/NSV13#119]
## Testmerges:

The testmerge that occured on the 2nd round of Nov 2nd, 2019

## Reproduction:

**Durasteel and Duranium materials and walls are conflated, and duranium sheet constructs durasteel walls, and durasteel sheet constructs duranium walls. Nothing is as it should be.**

Acquire duranium sheet and metal sheet from engineering.
**Read the following carefully. There are similar sounding words in what I'm about to write.**

Build a wall girder with metal and then apply **duranium sheets** to it. This will construct a **durasteel** wall.
Upon deconstructing the **durasteel wal**l with a welder, you will recieve **durasteel sheet**.
If you apply this **durasteel sheet** to the wall girder, you will construct a **duranium wall**.

It was at this point, I decided my mind was too fracked to find out what would happen next.

**Comment by Vasily2013** [comment]
PR test merged for last test (on 2 Nov) was #107
