### ISSUE TITLE
Synths can get mutations

### ISSUE THREAD

**Issue by deadmomo69** [DDMers/NSV13#134]
## Round ID: 
25

## Testmerges:
I'm unsure.

## Reproduction:
Be synth.
Get trapped in a radstorm.
Get mutations such as 'blind', 'mute', and others.
suffer because mutadone doesn't work.

Reproduction explains most of it- it also seems mutadone won't fix it, because synths don't metabolize chems and stuff?

**Comment by francinum** [comment]
Synths have been disabled for now.
Fixed in #160
