### ISSUE TITLE
Munitions Tech don't have access to viewscreens

### ISSUE THREAD

**Issue by deadmomo69** [DDMers/NSV13#143]
## Reproduction:
Click on viewscreen on the wall as a munitions tech, you can use it but it gives a buzz saying access denied, and puts 
![image](https://user-images.githubusercontent.com/37983463/69483861-a043bb80-0dfa-11ea-8380-73df8cb12b55.png)
a camera button each time on your screen.

**Comment by gryffinp** [comment]
I can confirm the same experience as a munitions tech.

**Comment by TheChosenEvilOne** [comment]
The extra camera buttons are caused by the same problem as #145

**Comment by francinum** [comment]
They have a req_access of `BRIDGE`

**Comment by francinum** [comment]
Fixed in #160
