### ISSUE TITLE
Viewscreens don't garbage collect viewscreen eyes

### ISSUE THREAD

**Issue by francinum** [DDMers/NSV13#145]
![](https://file.house/lxsk.png)

**Comment by TheChosenEvilOne** [comment]
https://github.com/DDMers/NSV13/blob/master/nsv13/code/modules/overmap/camera.dm#L97 expects stop_piloting to return true but it will never return true as there is no return and . is not being set.
Just make https://github.com/DDMers/NSV13/blob/master/nsv13/code/modules/overmap/camera.dm#L15 return TRUE at the end.
