### ISSUE TITLE
Synthetic having augmentation issues..again.

### ISSUE THREAD

**Issue by deadmomo69** [DDMers/NSV13#149]
## Reproduction:
Got augmented in robotics, walked around for a moment, and realized my head and chest were sent to the shadow-realm.
Basically same thing as my last issue regarding this

![image](https://user-images.githubusercontent.com/37983463/69484761-22d17880-0e05-11ea-9161-2942b6bb9ff0.png)

**Comment by Kmc2000** [comment]
I'm unable to reproduce this locally. Is there any further info you can provide?

**Comment by deadmomo69** [comment]
@Kmc2000 Seems to be fixed somehow now.
