### ISSUE TITLE
[HAMMERHEAD] No bot pathing nodes.

### ISSUE THREAD

**Issue by Freakycrafter** [DDMers/NSV13#152]
## Reproduction: Unlock a medibot and enable the patrol mode

The medibots dont seem to have a path mapping yet (or a broken one) and every time you enable their patrol mode it immeadietly disables again, so they are unable to patrol the station.

**Comment by francinum** [comment]
No AI nodes are mapped in, they're an utter fucking bitch to do and weren't finished for the Hammerhead.
