### ISSUE TITLE
[Hammerhead] HoS can't access the fighter ship hangar bay

### ISSUE THREAD

**Issue by dinnerwoerror** [DDMers/NSV13#198]
the head of SECURITY doesn't even get access to his own hangar bay, and this issue is only magnified by the fact that the security secure storage & arms storehouse (where the HoS office is) and the security brig (where literally the rest of the security department is) is separated by the hangar bay

**Comment by Karmic-Skink** [comment]
HoS is not HoD for fighters etc. Munitions/Ship Combat is intended to be its own department.

**Comment by dinnerwoerror** [comment]
so does that mean that for now, it's basically a headless department (kind of like cargo)

**Comment by Karmic-Skink** [comment]
MaA is head.

**Comment by dinnerwoerror** [comment]
well it appears that the issue i bring up here was never really an issue in the first place

off to the next one, my fellow racial slur

**Comment by Karmic-Skink** [comment]
Full implementation of department hasn't been completed at this stage.

**Comment by Vasily2013** [comment]
Not an issue.
