### ISSUE TITLE
mining doesn't exist

### ISSUE THREAD

**Issue by dinnerwoerror** [DDMers/NSV13#201]
yes, we all know about this one, but it would be good to make this official

the mining shuttle doesn't really exist, so there's nothing to really "mine", more like cut up walls and disassemble tables and chairs for those sweet materials and sell them back to daddy QM

cargo just gets a trash bag full of rare minerals (plasma, titanium, uranium, etc.) and that's basically all they get, merry christmas from CentCom

everything else you're gonna have to either salvage from the ship by cutting up walls and whatnot, or actually buying materials from the cargo console which can get expensive as balls (something like $18k for 50 sheets of plasteel)

**Comment by Karmic-Skink** [comment]
Did anyone try salvaging an enemy ship?

**Comment by dinnerwoerror** [comment]
probably not, because they get blown the frick up when their reactor overloads

**Comment by Karmic-Skink** [comment]
Incorrect. Salvage system stabilizes the wrecks.

**Comment by Vasily2013** [comment]
Mining now exists. Closing issue.
