### ISSUE TITLE
Bridge Radar is highly deceptive. 

### ISSUE THREAD

**Issue by SerJanko** [DDMers/NSV13#90]
[The Dradis](https://image.prntscr.com/image/XsFqvjr9QuKUFPDCAs6U3g.png) console's overlay image makes you believe that you're facing contacts, not that you are that single blue blip moving across the overmap.

I suggest replacing the Dradis image entirely with just a more traditional radar appearance, or some kind of representation of space since your ship won't be centered in it. Removes any confusion you might have, like trying to chase that blip on the radar for close to an hour.

As well, having the radar automatically update for the pilot would be a huge help. Perhaps expand on using the console individually, like giving information about nearby contacts.

**Comment by Kmc2000** [comment]
It should autoupdate, or at least, it did when testing...
